from django.urls import path

from .views import (
    InvitationAcceptView,
    InvitationCreateView,
    InvitationDeclineView,
    InvitationDetailView,
    MembershipDetailView,
    MembershipListView,
    OrganizationCreateView,
    OrganizationDetailView,
    OrganizationListView,
)

urlpatterns = [
    path(
        "",
        OrganizationListView.as_view(),
        name="organization-list",
    ),
    path(
        "create/",
        OrganizationCreateView.as_view(),
        name="create-organization",
    ),
    path(
        "<uuid:pk>/",
        OrganizationDetailView.as_view(),
        name="organization-detail",
    ),
    path(
        "<uuid:organization_id>/invitations/",
        InvitationCreateView.as_view(),
        name="create-invitation",
    ),
    path(
        "<uuid:organization_id>/members/",
        MembershipListView.as_view(),
        name="list-members",
    ),
    path(
        "<uuid:organization_id>/members/<uuid:membership_id>/",
        MembershipDetailView.as_view(),
        name="detail-member",
    ),
    path(
        "invitations/<uuid:token>/accept/",
        InvitationAcceptView.as_view(),
        name="invitation-accept",
    ),
    path(
        "invitations/<uuid:token>/decline/",
        InvitationDeclineView.as_view(),
        name="invitation-decline",
    ),
    path(
        "invitations/<uuid:token>/",
        InvitationDetailView.as_view(),
        name="invitation-detail",
    ),
]
