# Generated by Django 6.0.7 on 2026-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="declined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
